### ISSUE TITLE
Preparing the app to be published to Mac AppStore

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#10]
Figure out the following:

* How to prepare the app to be published to Mac AppStore
* Is it possible to have a beta tester's channel there? If not, what are the options for beta testers?
* What metadata do we need to supply in order to get the app published. Post the list here, we'll start preparing it.

**Comment by timirila1** [comment]
>What metadata do we need to supply in order to get the app published. Post the list here, we'll start preparing it.

- **Title** (required)
- **Subtitle** (optional)
- **Description** (required for new locale)
- Promotional text (optional)
- **Keywords** (required for new locale)
- **What's new Text** (required for new locale)
- **Support URL** (required for new locale)
- **Privacy policy URL** (required for new locale)
- [App Previews](https://help.apple.com/app-store-connect/#/dev4e413fcb8) (optional) 
- [Software screenshots](https://help.apple.com/app-store-connect/#/devd274dd925) (optional)
- **App Store Icon** (required)

Since this will initial uploading, we must provide all fields marked as required for new locale.


[App Store Connect docs](https://developer.apple.com/support/app-store-connect/)

[App Metadata Specification 5.10](https://help.apple.com/itc/appsspec/#/)

**Comment by ameshkov** [comment]
Let's provide some screenshots, though:

```
One of the following, with a 16:10 aspect ratio.
1280 x 800 pixels
1440 x 900 pixels
2560 x 1600 pixels
2880 x 1800 pixels
-- | --

* Title will be `AdGuard for Safari`

Everything else needs to be prepared, summoning @vbagirov here

**Comment by timirila1** [comment]
Also we need to make sure that the application is displayed correctly in the Dark mode of the new macOS Mojave

**Comment by timirila1** [comment]
>Is it possible to have a beta tester's channel there? If not, what are the options for beta testers?

This part of the issue moved here https://github.com/AdguardTeam/AdGuardForSafari/issues/14

**Comment by ameshkov** [comment]
@timirila1 one more thing about this issue: what kind of distributive does Mac AppStore require?

Verify that the one we build at the moment is enough to publish the app.
