### ISSUE TITLE
Open at login in background.

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdGuardForSafari#141]
Open in background only if app is opened at login.

**Comment by iDjay** [comment]
Would like to see that too :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by digitalqualms** [comment]
There's got to be a better way but one quick hack might be instead of calling os.uptime here: 
https://github.com/AdguardTeam/AdGuardForSafari/blob/2b34e734436284be6827567f2a487df6c38fe33a/ElectronMainApp/main.js#L122-L127

Call child_process.exec with the shell command:

`who | grep -i "$USER.*console"`

Sample output:

`myuser     console  Jun 21 00:18`

Then parse the time out of the output? Maybe fallback to uptime if there's not a valid response?

**Comment by ameshkov** [comment]
@digitalqualms well, this also looks like a workaround:)

Also, isn't it the same as checking uptime?

**Comment by digitalqualms** [comment]
It’s different than uptime because it’s the user’s current login time instead of the system’s boot time. That should be closer if you reboot for updates or something, then login an hour later.

**Comment by ameshkov** [comment]
Makes sense, thank you!

**Comment by devburke** [comment]
Came here to request this as well. Right now users cannot have AdGuard start blocking automatically after login without the app window opening first, either automatically at login, or manually. I'm pretty sure almost every single user would prefer for it to just quietly start working in the background.

Thanks!
