### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#299]
1. Make it enabled by default
2. Add "Disable hardware acceleration" option to general settings

**Comment by Mizzick** [comment]
It has been disabled cause of #110, #165 
I have just tested it and there is no issues with current build.

So do you really want to make such a low-level option in general settings?

**Comment by ameshkov** [comment]
@Mizzick well, that's what Slack does, and I think it makes sense.

**Comment by s4y** [comment]
Drive-by comment: It looks like that issue affects specific older Mac laptops because of problems with the integrated GPU. Chrome opted to force the discrete GPU on those machines instead of turning off acceleration completely. In an ideal world, Electron could automatically turn off hardware acceleration just on those machines and leave it on for other machines. As-is, a setting feels like overkill.
