### ISSUE TITLE
YouTube autoplay audio

### ISSUE THREAD

**Issue by linyangchen** [AdguardTeam/AdGuardForSafari#381]
### Issue Details

* AdGuard for Safari version: 1.7.4
* Environment name and version: Safari 13.1.2 (15609.3.5.1.3)
* Operating System: macOS Catalina 10.15.6
* Filters you use in AdGuard: most except language-specific, social widgets
* Any other browser extensions you have installed: none

### Actual Behavior

- go to www.youtube.com
- search "pink panther" in the youtube search box
- click the first result ("Official Pink Pantherl")
- browser directs to https://www.youtube.com/user/PinkPanther
- audio starts autoplay without showing any video. There's actually a video hidden behind the banner at the top.
- unable to disable the autoplay. I already have Safari media flags set to "disable inline video", and Auto-Play in Safari preferences set to "Never auto-play", but it still autoplays.
- Request for AdGuard to disable this autoplay.

If you go directly to https://www.youtube.com/user/PinkPanther, it doesn't autoplay. It autoplays only if you do what I described above (get to it via search results).

Same thing happens with the following channels (get to them via youtube search results):
https://www.youtube.com/user/CNN
https://www.youtube.com/user/scmp888
https://www.youtube.com/user/bbcnews

Probably the YouTube channels of most major corporations force this autoplay.

**Comment by Sam5883** [comment]
lol i had this issue, i figured out this issue was caused by the fanboy annoyances and/or web annoyances ultralist, disabling them and restarting mac fixed that issue for me, there was some videos that were hidden by the channel banner right? these filters seems problematic, i was having issues with youtube, twitter and many more websites. btw you're using outdated version of adguard, lastest official release is 1.8.2

**Comment by zzebrum** [comment]
@linyangchen @Sam5883 web annoyances ultralist is the problem here again. And unfortunately, nothing could be done with video autoplay from our side
