### ISSUE TITLE
Where are previuos AG for Safari versions?

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#420]
Hello,
I'm looking for AG for Safari v. 1.8.2 because with the last version I'm having some issue.
In https://github.com/AdguardTeam/AdGuardForSafari/releases there are only https://agrd.io/safari_release and https://agrd.io/safari_beta .
Maybe, it would be better to use direct links.

Thanks.

**Comment by ameshkov** [comment]
> I'm looking for AG for Safari v. 1.8.2 because with the last version I'm having some issue.

What kind of issues?

**Comment by ameshkov** [comment]
Version 1.8.2 beta:
https://uploads.adguard.com/AdGuard_Safari.app_1.zip

**Comment by superlex** [comment]
I think some elements aren't hiddend if in the page scriptlets/js scripts are injected (but these scriptlets/js scripts work).
Example:
```
apkmirror.com#%#//scriptlet('adjust-setInterval', '', '1000')
apkmirror.com##.promotedApp
```
promotedApp class is hidden only if I remove adjust-setInterval scriptlet.
I didn't have this issue with v .1.8.2, so I'd like to understand if it depend on the latest update.

**Comment by ameshkov** [comment]
Is it reproduced with example.org and `example.org##body`?

**Comment by superlex** [comment]
Yep:
```
example.org##body
example.org#%#alert("example");
```
with alert bod is not hidden.

**Comment by ameshkov** [comment]
Filed a new bug report about that:
https://github.com/AdguardTeam/AdGuardForSafari/issues/421

**Comment by superlex** [comment]
Thank you @ameshkov !
All good with v 1.8.2, so definitely v.1.8.5 issue.

**Comment by zecanard** [comment]
> Version 1.8.2 beta:
> https://uploads.adguard.com/AdGuard_Safari.app_1.zip

Thank you for this. I’ve been having issues since 1.8.3 beta that are very hard to reproduce. But to put it simply, AdGuard just stops working. Disabling/reenabling from the menu bar doesn’t do anything, nor disabling every individual extension from within Safari Preferences, restarting Safari, restarting macOS…

One time, I’ve had this happen after disabling, and immediately reenabling, AdGuard from the menu bar. Other times, it happens after modifying my custom-filters file. One time, going from the beta standalone to the Mac App Store version corrected the issue, then it cropped up again, and AdGuard simply refused to work again after that. 1.8.2 works flawlessly.

**Comment by zecanard** [comment]
> Version 1.8.2 beta:
> https://uploads.adguard.com/AdGuard_Safari.app_1.zip

Thank you for this. Is there a way to block AdGuard from updating itself automatically?

I’ve been having issues since 1.8.3 beta that are very hard to reproduce. But to put it simply, AdGuard just stops working. Disabling/reenabling from the menu bar doesn’t do anything, nor disabling every individual extension from within Safari Preferences, restarting Safari, restarting macOS…

One time, I’ve had this happen after disabling, and immediately reenabling, AdGuard from the menu bar. Other times, it happens after modifying my custom-filters file. One time, going from the beta standalone to the Mac App Store version corrected the issue, then it cropped up again, and AdGuard simply refused to work again after that. 1.8.2 works flawlessly.

**Comment by ameshkov** [comment]
@zecanard try the latest beta or release (v1.8.6), there was a pretty serious bug that is now fixed.

> Is there a way to block AdGuard from updating itself automatically?

@Mizzick ping, does "Update interval" applies to app update or is it only for filters updates?

**Comment by zecanard** [comment]
> @zecanard try the latest beta or release (v1.8.6), there was a pretty serious bug that is now fixed.
That’s the version I had to back out of. I was on 1.8.5 from the Mac App Store, which seemed to be working fine (both standalone channels weren’t blocking ads). Then it auto-updated to 1.8.6, which also seemed to work fine for a bit. But then I did something that caused AdGuard to stop blocking ads (I think it was updating my custom filter), and from there it simply would not block ads no matter what I did.

> @Mizzick ping, does "Update interval" applies to app update or is it only for filters updates?

I’ve tried setting that value to Do not update, and it immediately updated upon launching the app. On the bright side, applying the update requires an app restart, so as long as I don’t quit it, it should stay on 1.8.2.

**Comment by ameshkov** [comment]
> I think it was updating my custom filter

Do you mind sharing the filter (or at least the rules that you've added last)?

**Comment by Mizzick** [comment]
> @Mizzick ping, does "Update interval" applies to app update or is it only for filters updates?

Only for filter updates. 
The app actually check updates on UI startup and every time "about" tab is opened.

**Comment by zecanard** [comment]
@ameshkov I’d mistakenly restored my previous custom-filters file with the rule `||*^$ping`. AdGuard started blocking every page, so I removed that line, updated filters in AdGuard, and then nothing was being blocked anymore.

You may also want to try disabling, then quickly reenabling AdGuard. That often causes problems for me; it may be normal, since disabling isn’t instantaneous, but hopefully a workaround can be implemented to avoid race conditions.

**Comment by ameshkov** [comment]
> You may also want to try disabling, then quickly reenabling AdGuard. That often causes problems for me; it may be normal, since disabling isn’t instantaneous, but hopefully a workaround can be implemented to avoid race conditions.

Please note, that it may take Safari up to 30 seconds to apply content blockers changes.

Other than that, I can't reproduce any issues:(

**Comment by zecanard** [comment]
Okay, I was able to narrow it down to [AdGuard French Filter](https://github.com/AdguardTeam/AdGuardForSafari/issues/429#issuecomment-734965529).
