### ISSUE TITLE
Annoying update nag screens disturb workflow

### ISSUE THREAD

**Issue by MBarti** [AdguardTeam/AdGuardForSafari#486]
Everytime there's a filter update (I've set checking to 48h), I get a nag screen to uptade AdGuard.

If I allow the update, I need to close Safari and all my tens of open tabs.

If I CANCEL it, it still disturbs the workflow by stealing the focus from Safari and relaunching Adguard in the background - this is very annoying.

Updates should be:
- either fully silent (if possible)
- or allowed to be checked more rarely (e.g. 1/week, not only 48h as maximum)
- and when cancelling - not steal the focus from the Safari window

**Comment by ameshkov** [comment]
Hm, but it is supposed to be silent.

What nag screen are you talking about? Could you please show it?

**Comment by TheHasagi** [comment]
Closed due to no response. Should be reopened if needed.

**Comment by kristojorg** [comment]
I am having this issue as well. The nag screen I see is an OSX alert that I must "Close Safari in order to update Adguard". I then have the option to quit safari or cancel. If I cancel, it relaunches AdGuard and steals focus. I just went through the process, so I'll have to post a screenshot next time it comes up. I am running Big Sur 11.1 Beta and Safari 14.0.2

**Comment by ameshkov** [comment]
I doubt we can do anything with that, sounds like a MacOS issue.

**Comment by MBarti** [comment]
How about making the „cancel” button actually, you know, cancel? Otherwise it’s just bad design, not a MacOS issue.

**Comment by kristojorg** [comment]
Seems unnecessarily snarky @MBarti ... You're also welcome to make a PR I assume.

@ameshkov is it true that Safari must be quit in order to update? If that's not supposed to be true then maybe we can somehow avoid this alert and let it update in the background while Safari is still running.

**Comment by ameshkov** [comment]
@MBarti @kristojorg 

You might've misunderstood me. 

1. What you're seeing has nothing to do with filter updates, this is about the app update
2. App updates are managed by App Store. Nowhere in the app we check if Safari is running or show any alerts.
3. I suppose the standalone AdGuard version does not suffer from this. However, closing Safari is indeed safer and may be needed to properly update the extensions.

**Comment by kristojorg** [comment]
Thanks for your explanation @ameshkov. I understand that it's not an alert rendered explicitly by AdGuard, but it does seem like it should be avoidable. Perhaps it is something that can be configured, because I don't see popups like this for any other app or extension. 

What do you mean by # 3 there? Do you think this would be solved by downloading AdGuard outside of the app store?

**Comment by ameshkov** [comment]
> What do you mean by # 3 there? Do you think this would be solved by downloading AdGuard outside of the app store?

Yep, I think that the issue is caused by App Store managing updates, it knows that the app includes Safari extensions and that's why it prompts to close Safari first. With the non-appstore version the updates are managed by AdGuard itself so there're no extra prompts.

**Comment by kristojorg** [comment]
Hmmm I did just have a look through the App Extension docs and it doesn't look like there is any configurability for this either. Disappointing. But at the same time I find it hard to believe that Apple will require shutting down safari any time an extension needs to update, so maybe I'm missing something
