### ISSUE TITLE
AdGuard messed up YouTube's UI

### ISSUE THREAD

**Issue by MrNorthernWolf** [AdguardTeam/AdGuardForSafari#536]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.8.10
* Environment name and version: Safari 14.0.3 and Safari Technology Preview 14.2
* Operating System: Big Sur 11.2.1
* Filters you use in AdGuard: Check the attached .log file
* Any other browser extensions you have installed: No

### Expected Behavior
AdGuard somehow breaks YouTube, it worked correctly for a while but now AdGuard will mess up YouTube's UI, check the attached screenshot, and notice how videos goes under the profile banner, once AdGuard is turned off the UI goes back to normal.
### Actual Behavior
AdGuard messed up YouTube's UI 

### Screenshot
<img width="1428" alt="Screen Shot 2021-02-22 at 6 24 34 PM" src="https://user-images.githubusercontent.com/79469305/108738719-97c9bb80-753c-11eb-8b78-8534d21d1f59.png">
</summary>

### Additional Information
I also have a .log file ready to go.

[adg_safari_logs_1614011094654.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/6023501/adg_safari_logs_1614011094654.zip)

**Comment by crgmrgn** [comment]
Seeing similar here, although the biggest issue is that it causes the left sidebar content to be positioned vertically too high, such that the YouTube logo and hamburger obscure the top 3x items in the sidebar. If you scroll the content pane upward (which takes the attached logo bar with it), you can glean some of the items in the sidebar, but not all. 

It seems that the vertical position of the sidebar has been derived from the screen origin, rather than the active window or similar, which offsets the sidebar by about the top ~50-60px (window header + tab bar + YT logo bar?).

**Comment by MrNorthernWolf** [comment]
I noticed that too on the sidebar, subscriptions tab actually disappears and it will lift the rest of the website UI up.

**Comment by AdamWr** [comment]
Hello,

Do you have `Web Annoyances Ultralist` enabled in AdGuard settings?
If so, it's probably related to this issue - https://github.com/yourduskquibbles/webannoyances/issues/287

Could you please try to update filters or add this rule to user filter:
`youtube.com#@$##contentContainer { padding-top: 0 !important; }`
or just disable `Web Annoyances Ultralist` then wait about 30-60 as changes will be applied (please do not close AdGuard) and check if issue still occurs?

**Comment by Oleg-Chashko** [comment]
Hi @MrNorthernWolf 

One of the filters is causing this problem. Disable one at a time until you find the filter causing the problem. Uvas enabled about 23 filters, judging by the log, I recommend disabling unnecessary filters.

**Comment by crgmrgn** [comment]
Interesting, checked this morning and the issue with sidebar visibility (and scrolling) is resolved. Checking the filters, the `Web Annoyances Ultralist` that was potentially incriminated has not seen an update since ~1wk ago (v1.0.7.13), so no fix came from there …

The `AdGuard Annoyances filter` though (v2.0.72.45) is extremely recent, was it the real issue? Or did someone push the work-around via the AdGuard filter. 

Just odd that I settled in this AM to do some testing/elimination and the issue was resolved for me (macOS 10.13.6, AdGuard 1.8.10).

**Comment by AdamWr** [comment]
We had a lot of reports with issues like this, for example - https://github.com/AdguardTeam/AdguardFilters/issues/74155#issuecomment-782886710 and many below, so yesterday I added a fix to AdGuard Base filter - https://github.com/AdguardTeam/AdguardFilters/commit/e6f34f72fe27674a0360610b583e35511bd396de until it will be fixed in `Web Annoyances Ultralist`.

**Comment by MrNorthernWolf** [comment]
I confrim this issue as FIXED also, changes that @AdamWr did fixed the issue.

You can close this issue if you like.

**Comment by crgmrgn** [comment]
> We had a lot of reports with issues like this, for example - [AdguardTeam/AdguardFilters#74155 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/74155#issuecomment-782886710) and many below, so yesterday I added a fix to AdGuard Base filter - [AdguardTeam/AdguardFilters@e6f34f7](https://github.com/AdguardTeam/AdguardFilters/commit/e6f34f72fe27674a0360610b583e35511bd396de) until it will be fixed in `Web Annoyances Ultralist`.

Ah, thought that might be it … thanks.
