### ISSUE TITLE
AdGuard for Safari and extensions will not close.  Tried to delete app and reinstall but can't delete.  Pls give instructions to do this.

### ISSUE THREAD

**Issue by markwm1007** [AdguardTeam/AdGuardForSafari#669]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment]
@markwm1007 Could you give a bit more information? You can't pause AdGuard protection or can't close the app itself?

In order to reinstall AdGuard for safari you need to:
1. Uncheck all AdGuard for Safari extensions in **Safari Preferences**  --> **Extensions** (if available)
2. In Finder press `Shift+Command+G`, find the following paths and and delete these directories:
`~/Library/Application Support/AdGuardSafariApp`
`~/Library/Containers/ - all directories started with com.adguard.safari.AdGuard`
`~/Library/GroupContainers/TC3Q7MAJXF.com.adguard.safari.AdGuard`
`~/Library/Preferences/com.adguard.safari.AdGuard.plist`
3. Quit all "AdGuard" and "cfprefsd" processes in **Activity monitor**
4. Delete AdGuard for Safari app
5. Install the [latest version](https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.10.4)

**Comment by Birbber** [comment]
@markwm1007 Any news?

**Comment by markwm1007** [comment]
Fixed it by restarting to quit the application. Thanks 

Sent from Mark McGroary 

On Dec 14, 2021, at 2:33 AM, Anna ***@***.***> wrote:

﻿
@markwm1007 Any news?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Birbber** [comment]
I'm closing this issue then. Please re-open if needed.
