### ISSUE TITLE
Enabling filters doesn't work

### ISSUE THREAD

**Issue by andreusanchez** [AdguardTeam/AdGuardForSafari#761]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
Version 1.11.7 (220)
* **Environment name and version:**
Safari 16.1 (18614.2.9.1.12)
* **Operating system and version:**
MacOS Ventura 13.0.1
* **Filters you use in AdGuard:**
N/A
* **Any other browser extensions you have installed:**
Lastpass

### Expected Behavior
Enabling a specific filter doesn't work as expected
### Actual Behavior
When enabling an specific filter inside i.e Privacy doesn't get applied or saved, so when you click on Privacy you see the option is disabled instead of enabled.
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Versty** [comment]
@andreusanchez It would be very helpful if you could record the video of this bug. 

We would like to take a look into your logs as well.
Please follow this steps to properly collect and send logs: 

1. Make sure all Safari content blockers are enabled;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the extension settings --> **Export logs and system info**;
4. Send the archive to `apple@adguard.com` and mention in the subject this issue number and a period of time the issue was reproduced at.

**Comment by Versty** [comment]
@andreusanchez Any updates?

**Comment by Versty** [comment]
@andreusanchez Thank you for the quick answer! 
Please reopen if the issue repeats.
