### ISSUE TITLE
Adguard UI keeps appearing every time I come out of sleep or reboot

### ISSUE THREAD

**Issue by cmadparty** [AdguardTeam/AdGuardForSafari#797]
Hello - I'm a long time user and love Adguard.  I have it on my iPhone and Mac.  However, on my Mac, the UI appears in the taskbar and opens as a window every time I log on my computer or reboot.  If I set it to not run at startup, the software appears to be inactive.  I think there is a bug where you should be able to have this running in the browser and background without having the icon appear in the taskbar and the UI pop up every time you log onto your machine.

Thanks.

**Comment by jslawler** [comment]
#746

**Comment by Versty** [comment]
@cmadparty This bug is related to notifications from the App Store/TestFlight apps on Ventura MacOS.  We are currently looking for an option to fix it. 
As a temporary solution I would recommend you update to the latest version (1.11.10) or uninstall this version from App Store and install the version from our [direct link](https://agrd.io/safari_release). 

If you would like to discuss this issue further please continue in #746
