### ISSUE TITLE
Question about script and style rules

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardForSafari#80]
Hi,
thank you very much for this new app/extension :)

However, it looks like AdGuardForSafari doesn't support script and style rules: is it because new Safari limitations?
Then, if it is, maybe Safari filter lists ([e.g.](https://filters.adtidy.org/extension/safari/filters/2.txt)) should be changed in order to not include them ([e.g.](https://filters.adtidy.org/ios/filters/2.txt)).

### Your environment

* AdGuard for Safari version: 1.0.1
* Environment name and version: Safari 12.0.1
* Operating System: macOS High Sierra 10.13.6
* Filters you use in AdGuard: default
* Any other browser extensions you have installed: none

**Comment by ameshkov** [comment]
> is it because new Safari limitations?

Yeah. The rules syntax is quite limited, basically the same as on iOS.

> Then, if it is, maybe Safari filter lists (e.g.) should be changed in order to not include them (e.g.).

Good catch:) We'll do it eventually when the old-style extensions are completely disabled by Apple (they still can be used for now).

Created a task just so that we don't forget about it:
https://github.com/AdguardTeam/FiltersCompiler/issues/27
