### ISSUE TITLE
User Rules not working

### ISSUE THREAD

**Issue by jgonion** [AdguardTeam/AdGuardForSafari#830]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS: 13.2.1
- Safari version:16.3
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

User Rules are:
###google_ads_iframe_\/331690308\/df_des_incontent_blu_0
###outbrain_widget_0
outbrain.com
track.com

### Expected Behavior

Expect both outbrain.com and track.com to be blocked.

### Actual Behavior

AdGuard blocks the *last* item in the list.
With the list above, it blocks track.com, but not outbrain.com.
If I swap the positions of these two rules, it blocks outbrain.com, but not track.com.

### Screenshots

<img width="940" alt="Screenshot 2023-03-18 at 9 00 05 AM" src="https://user-images.githubusercontent.com/38082487/226117054-15e37316-f27d-44ac-aade-b3d7a727c21a.png">

**Comment by Versty** [comment]
@jgonion Hi! 
Please try out this rules: 
`||outbrain.com^`
`||track.com^`
In order to properly block web elements you need to use [special syntax](https://adguard.com/kb/general/ad-filtering/create-own-filters/). Also, you can block the element directly from the browser page, click the AdGuard icon in the toolbar ->  Block an element -> Select desired element -> Block. 
New blocking rule will appear in the User rules list.
