### ISSUE TITLE
AdGuard breaks duckduckgo.com used as default search engine

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardForSafari#911]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: ?
- Safari version: ?
```

### Issue Details

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/162926#issuecomment-1747321983

Scrolling of the page is not working when search in DuckDuckGo using the omnibox.

@thommesborg 
> It's not as easy to repro as I thought. First, I supposed AdGuard enhanced
blocking to be the culprit. But no. It happens randomly with different
search terms. If I open a new tab and search for the same phrase that lead
to a dead results-page before, it repros in maybe one or two further new
tabs and the third one works as expected.
But it happens more often than it should, and always with DuckDuckGo. And,
no, DDG don't show a cookie-consent page when AdGuard was disabled.

### Expected Behavior

Scrolling is working.

### Actual Behavior

Sometimes scrolling is not working.

**Comment by alexx7311** [comment]
@thommesborg Hello! Please go to Safari settings > Extensions, disable all extensions except for AdGuard for Safari, and check if the problem persists. This method allows the browser to use only Advanced rules. If the problem occurs again, there is a good chance that the problem is with these rules.

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardForSafari/assets/114913601/e961f430-fd95-4739-96c9-5414b9ea9b6a)

</details>

**Comment by thommesborg** [comment]
Hi, there are no other extensions in use. I’ve stated that earlier, too. The issue still persist. Regards,Tom      <~>Am 13.11.2023 um 15:09 schrieb alexx7311 ***@***.***>:﻿
@thommesborg Hello! Please go to Safari settings > Extensions, disable all extensions except for AdGuard for Safari, and check if the problem persists. This method allows the browser to use only Advanced rules. If the problem occurs again, there is a good chance that the problem is with these rules.

  Screenshot 1

**Comment by alexx7311** [comment]
@thommesborg We're referring to the extensions of AdGuard for Safari itself. There's **AdGuard Custom, AdGuard General, AdGuard Other, AdGuard Privacy, AdGuard Security, AdGuard Social and AdGuard for Safari**. Please disable all these extensions except `AdGuard for Safari` and check if the problem persists.

**Comment by alexx7311** [comment]
@thommesborg 
This means the problem is with Advanced Rules. Please try the following:
1. Disable all AdGuard extensions except AdGuard for Safari again.
2. Disable one of the active filters.
3. Open a new incognito tab in Safari and see if the problem persists. 
4. If the problem recurs, disable another filter.

Repeat steps 2-4 until the problematic filter is found.

**Comment by thommesborg** [comment]
My God!!!!!I did all this. I stated that before. I’ve spent a complete afternoon with disabling and re-enabling filter by filter. I also stated, that the issue persists. Now it’s good. The ball is on your side. Act as you like. I switched to the Brave browser that has implemented ad- and privacy-filters and don’t show this issue. Regards, live long and prosper. 🖖🏼     <~>Am 22.11.2023 um 14:45 schrieb alexx7311 ***@***.***>:﻿
@thommesborg
This means the problem is with Advanced Rules. Please try the following:

Disable all AdGuard extensions except AdGuard for Safari again.
Disable one of the active filters.
Open a new incognito tab in Safari and see if the problem persists.
If the problem recurs, disable another filter.

Repeat steps 2-4 until the problematic filter is found.
